# -*- coding: utf-8 -*-
"""Spam Mail detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JvN7Q_CD88FU5M9VQh2zb1g_KX-LhhSZ
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
from  sklearn.metrics import accuracy_score

raw_mail_data = pd.read_csv('/content/mail_data.csv')

raw_mail_data.head()

raw_mail_data.shape

raw_mail_data['Category'].value_counts()

raw_mail_data.loc[raw_mail_data['Category'] == 'ham','Category'] = 0
raw_mail_data.loc[raw_mail_data['Category'] == 'spam','Category'] = 1

raw_mail_data.head()

"""**ham --> 0**

**spam -->1**
"""

X = raw_mail_data['Message']
Y = raw_mail_data['Category']

print(X)

print(Y)

X_train, X_test, Y_train, Y_test = train_test_split(X,Y,random_state=2, test_size=0.2,stratify=Y)

print(X.shape,X_train.shape,X_test.shape)

feature_extraction = TfidfVectorizer(min_df=1,stop_words = 'english',lowercase = True)

X_train_features = feature_extraction.fit_transform(X_train)
X_test_features  = feature_extraction.transform(X_test)

print(X_train_features)

Y_train = Y_train.astype('int')
Y_test =  Y_test.astype('int')

model = LogisticRegression()

model.fit(X_train_features,Y_train)

training_data_prediction = model.predict(X_train_features)
accuracy_on_training_data = accuracy_score(Y_train,training_data_prediction)
print('Accuracy score on training data',round(accuracy_on_training_data*100,2))

test_data_prediction = model.predict(X_test_features)
accuracy_on_test_data = accuracy_score(Y_test,test_data_prediction)
print('Accuracy score on test data',round(accuracy_on_test_data*100,2))

input_data = ["XXXMobileMovieClub: To use your credit, click the WAP link in the next txt message or click here>> http://wap. xxxmobilemovieclub.com?n=QJKGIGHJJGCBL"]
input_data_features = feature_extraction.transform(input_data)
prediction = model.predict(input_data_features)

if(prediction[0] == 0):
  print('Ham mail')
else:
  print('Spam mail')

